### ISSUE TITLE
weird hacking tool

### ISSUE THREAD

**Issue by Slydylan** [EvaisaDev/LethalThings#12]
i understand that its math based but from what i could tell there are a lot of features missing
you can be required to enter a double digit number based on the math question and you'll need to input only the first of those two numbers
or if you have to write a negative number you'll just write it as a positive otherwise its incorrect
this is so counter intuitive and it takes multiple tries to get right one time. any plans to improve?

**Comment by EvaisaDev** [comment]
You are misunderstanding how the math works.
Mod(|5+7|) means Modulo 10 of the absolute value of 5 + 7, so if the number goes past 10 you take the remainder of the number after you subtracted 10.
The pipes || indicate that it is the absolute value, so if it is 5 - 7, then we take the answer and make it positive. so the answer would be 2

**Comment by Slydylan** [comment]
bro that is not simple math i am crying rn

**Comment by Slydylan** [comment]
i mean i get it, its nerdy, and it requires people to learn. that's cool. but please add this explanation somewhere in the computer

**Comment by Slydylan** [comment]
can you get double digits in the questions? what if you get a 1 - 12? what then how do you answer that

**Comment by Slydylan** [comment]
yeah i just went and looked up modulos and am so confused now

**Comment by EvaisaDev** [comment]
> can you get double digits in the questions? what if you get a 1 - 12? what then how do you answer that. now are we adding 10?

You only get singe digits in the questions.

**Comment by EvaisaDev** [comment]
> i mean i get it, its nerdy, and it requires people to learn. that's cool. but please add this explanation somewhere in the computer. when the game requires you to learn stuff outside of the game just to play the game it is immersion breaking..
> 
> honestly outside of maybe programming i cant think of a single real world application for this type of math... i paid attention to multiplication and division and shi- because i understood what i needed it for. if i ever learned this i threw it into the garbage...

The explanation is already in the info command of the terminal.

**Comment by Slydylan** [comment]
not sure if its a compatibility problem but i cannot use the word info in the terminal

**Comment by Slydylan** [comment]
got it. thanks
