### ISSUE TITLE
lightning striking in building?

### ISSUE THREAD

**Issue by dezji** [EvaisaDev/LethalThings#15]
Not 100% sure how but even since we added lethalthings to our somewhat extensive library of mods, we are now consistently able to be struck by lightning while inside of buildings?? We've never had this issue before, and on the same day we installed the mid (and none others since) we seem to be getting struck if we have any metal objects on us, anywhere inside any library or facility, regardless of where...the only safe place is inside the ship, anywhere else we can be struck in any planet so long as it is stormy..

**Comment by EvaisaDev** [comment]
Not an issue i have seen before, neither one lethal things could possibly cause so idk sorry.
