### ISSUE TITLE
Unable to TAB out of terminal

### ISSUE THREAD

**Issue by AlokinWolffe** [EvaisaDev/LethalThings#2]
Upon loading the game for the first time, the mod causes the inability to leave the terminal.
Only option is to ALT+F4 the game. :C

Maxwell looks very cute on the photos though :3

![Snímek obrazovky 2023-12-09 223933](https://github.com/EvaisaDev/LethalThings/assets/69575271/e1cd9193-18bb-4173-a071-58b7a5e96966)
![20231209223911_1](https://github.com/EvaisaDev/LethalThings/assets/69575271/e25277fc-8004-453e-b1bb-e5b434e189ce)
![20231209223916_1](https://github.com/EvaisaDev/LethalThings/assets/69575271/e1a61af8-1b3d-4eb6-a6a5-e2a0f600ac76)

**Comment by EvaisaDev** [comment]
This was because of the v45 game update yesterday, should be fixed with the latest LethalLib revision
