### ISSUE TITLE
(bug) Toy Hammer broken in v49

### ISSUE THREAD

**Issue by HamedAlmanthari** [EvaisaDev/LethalThings#26]
hello. when you hit with the toy hammer, it gets stuck in your hand and you can't drop it or interact with anything. this is the error i get in the console after i use the hammer.
![image](https://github.com/EvaisaDev/LethalThings/assets/133137232/c1060d68-fbd0-4529-8fa9-39d16cd83586)
i don't know if this is caused by another mod conflict or if v49 broke it.

**Comment by KiloWutt** [comment]
Hey there, just wanted to add that shovels are broken too, can't do anything but throw it away after one swing. This happens when you have LethalLib installed, even without the main mod.

**Comment by HamedAlmanthari** [comment]
so LethalLib is broken?

**Comment by EvaisaDev** [comment]
no, this is an issue with lethal things, all that is required to fix it is for the mod to be rebuilt against the new game assemblies.
I already fixed the issue for the next lethal things update which will be released after i finish testing.
