### ISSUE TITLE
Pinger problem

### ISSUE THREAD

**Issue by Uniteria** [EvaisaDev/LethalThings#28]
Hi, thanks for adding new item!

Sadly it's bugged, i mean whenever i try to purchase it typing "pinger" store moves by one and for example asks me to buy shotgun which is next in line. I disabled shotgun mod, tried again and now it doesn't let me buy it. When typing "pinger" and pressing enter, nothing happens.

Screen shots aint necessary, i think i explained that problem well. Thanks!

**Comment by EvaisaDev** [comment]
This was caused by a bug with LethalLib, LethalLib 0.11.2 should fix it, which i just pushed to thunderstore.

**Comment by Uniteria** [comment]
> This was caused by a bug with LethalLib, LethalLib 0.11.2 should fix it, which i just pushed to thunderstore.

Thank you very much <3
