### ISSUE TITLE
Maxwell and Spraypaint cans do not mixwell

### ISSUE THREAD

**Issue by bruxisma** [EvaisaDev/LethalThings#3]
Hello!

Due to an accident, maxwell was sprayed with the new v45 spray paint can and as you can see in the cropped image (names of friends are obscured) the dingus (your words in the code not mine) turned into a special window and lost his opaqueness. This same effect only occurs on lethalthing related items. I assume this is either a material bug, or something to do with patched shaders.

Side note: Thank you for this mod, it adds a lot of fun for my group of friends (we do disable a few items for balance).

![image](https://github.com/EvaisaDev/LethalThings/assets/63051/7ed63e29-5e2e-41d3-89aa-6d9095a84feb)

**Comment by EvaisaDev** [comment]
that's so fucking goofy, i have no idea why that would happen. I use the same shaders as the game does.

**Comment by EvaisaDev** [comment]
fixed by making all the items unspraypaintable.

**Comment by bruxisma** [comment]
Thank you!
